# name: CodeCov

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   build:
#     # The type of runner that the job will run on
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#     - uses: codecov/codecov-action@v1.0.6
#       with:
#       # Repository upload token - get it from codecov.io. Required only for private repositories
#         token: c8f5a876-56b4-4bb5-bfc0-78381ccfa0bc
#       # Specify whether or not CI build should fail if Codecov runs into an error during upload
#         fail_ci_if_error: false